// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ub6ffsU38jc8BIHNDIUBFmGvkRlBSBg',
    appId: '1:493901468844:web:6f0b68be3f36bc515e7b09',
    messagingSenderId: '493901468844',
    projectId: 'bank-app-e3f34',
    authDomain: 'bank-app-e3f34.firebaseapp.com',
    storageBucket: 'bank-app-e3f34.appspot.com',
    measurementId: 'G-B12LC8XTQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkZo3uScCQCTF8Qnlhos7oxMthzGLyapE',
    appId: '1:493901468844:android:7da3d57d124c75635e7b09',
    messagingSenderId: '493901468844',
    projectId: 'bank-app-e3f34',
    storageBucket: 'bank-app-e3f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkGdJ6y1-y-CKdh8nnIzxHnmLwQ_eJD2c',
    appId: '1:493901468844:ios:5fded38e3aac50ab5e7b09',
    messagingSenderId: '493901468844',
    projectId: 'bank-app-e3f34',
    storageBucket: 'bank-app-e3f34.appspot.com',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkGdJ6y1-y-CKdh8nnIzxHnmLwQ_eJD2c',
    appId: '1:493901468844:ios:5fded38e3aac50ab5e7b09',
    messagingSenderId: '493901468844',
    projectId: 'bank-app-e3f34',
    storageBucket: 'bank-app-e3f34.appspot.com',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_ub6ffsU38jc8BIHNDIUBFmGvkRlBSBg',
    appId: '1:493901468844:web:384459d59d9a47605e7b09',
    messagingSenderId: '493901468844',
    projectId: 'bank-app-e3f34',
    authDomain: 'bank-app-e3f34.firebaseapp.com',
    storageBucket: 'bank-app-e3f34.appspot.com',
    measurementId: 'G-LKBJ25X4GY',
  );
}
